name: Deploy SIMAGAS ke cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Sinkronisasi Otomatis ke cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode dari GitHub
      uses: actions/checkout@v4

    - name: Kirim File Inti ke Backend
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /backend_simagas/
        exclude: |
          public/**
          .env
          vendor/**

    - name: Kirim Aset Publik ke Public_html
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: /public_html/
        exclude: |
          index.php